### ISSUE TITLE
Aceita entrar em minha organização?

### ISSUE THREAD

**Issue by caue-alves** [Felipe-Souza-Pereira-Lima/Felipe-Souza-Pereira-Lima.github.io#1]
Bom dia Felipe, vi que você tem certas habilidades em Python 3 e gostaria de peguntar se você gostaria de entrar na minha organização, @Val-Assistant, que produz a Val Assistant. Todo seu core é feito em Python e acho que podemos todos aprender. A organização é open-source e voluntária, espero sua resposta. 
P.S: Abri um pull request em seu DsaRepositories com algumas mudanças, dê uma olhada pois acho que ficaram boas ;)

**Comment by Felipe-Souza-Pereira-Lima** [comment]
Claro que aceito entrar em sua organização, darei uma ulhada no @DsaRepositories! Acho que segunda-feira vou publicar no GitHub um emulador de Terminal GNU/Linux, meu computador não quer iniciar então terei que reinstalar o Windows 10

**Comment by caue-alves** [comment]
Ok, enviei o pedido, agora é só aceitar ;)
